########################### Code Overview #####################################
# This script plots dihedral angle distributions from the data files
# generated by the get_dihedral_distribution.py script provided. 

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize, LinearSegmentedColormap
from matplotlib.cm import ScalarMappable

folders = ['sPS', 'aPS_0.25', 'aPS', 'aPS_0.75', 'iPS']
tacticity = np.array([0.0, 0.25, 0.5, 0.75, 1.0])
xvals = np.linspace(0, 360, 500)

tacticity_colors = {
    0.00: '#00008B',   # deep blue
    0.25: '#6495ED',   # cornflower blue
    0.50: '#9370DB',   # medium purple (transition)
    0.75: '#DC143C',   # crimson
    1.00: '#8B0000',   # dark red
}

base_cmap = plt.get_cmap('turbo')
custom_cmap = LinearSegmentedColormap.from_list(
    "custom_tacticity",
    [tacticity_colors[t] for t in sorted(tacticity_colors)],
    N=256
)

colors = [tacticity_colors[t] for t in tacticity]

plt.figure(figsize=(5.5, 5))
for i, folder in enumerate(folders):
    data = np.loadtxt(f'./../{folder}/dihedrals.dat')[:, 1]
    plt.plot(xvals, data, color=colors[i], linewidth=2.0, label=folder)

plt.xlabel(r'Angles', fontweight='bold')
plt.ylabel(r'Dihedral Distribution', fontweight='bold')
plt.xticks([0, 90, 180, 270, 360])
ymax = max(np.loadtxt(f'./../{folder}/dihedrals.dat')[:, 1].max() for folder in folders)
plt.yticks([0.33333*ymax, 0.66666*ymax], ['', ''])  # <-- scaled marks, no labels
plt.ylim(0,)
plt.xlim(0, 360)

sm = ScalarMappable(cmap=custom_cmap, norm=Normalize(vmin=0.0, vmax=1.0))
sm.set_array([])
cbar = plt.colorbar(sm, ticks=[0, 0.25, 0.5, 0.75, 1.0])
cbar.set_label('Tacticity')
cbar.ax.tick_params(size=0)
plt.savefig('dihedrals_PS_new.png', bbox_inches='tight', dpi=300, transparent=True)
plt.close()